FROM windowsservercore:10.0.14300.1000

LABEL Description="Nginx" Vendor=Nginx" Version="1.1.13"

COPY nginx /nginx
COPY nginx.conf /nginx/conf/nginx.conf

CMD [ "/nginx/nginx.exe" ]


# docker build -t=andrew/revproxy:latest .
# docker run --rm -t -i andrew/revproxy cmd.exe